version: '3.8'

services:

  nginx: 
    restart: always
    image: nginx:latest
    container_name: omini-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  database:
    restart: always
    image: "postgres:14.0-alpine"
    container_name: omini-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: omini_db
      POSTGRES_USER: omini_user
    
  backend:
    restart: always
    build: ./src/backend
    container_name: omini-backend
    environment:
      - DATABASE_URL=postgres://omini_user:example@database:5432/omini_db
      - SERVER_HOST=0.0.0.0:5000
      - DB_NAME=omini_db
      - DB_USER=omini_user
      - DB_PASSWORD=example
      - DB_HOST=database
      - DB_PORT=5432
    ports:
      - 5000:5000
    links:
      - database
    depends_on:
      - database
  