[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web= "^4"
actix-cors= "^0.6.2"
serde = { version = "^1", features = ["derive"]}
serde_json = "^1"
serde_yaml = "^0.9"
env_logger = "0.9.0"
log = "^0.4"
derive_more = "^0.99"
diesel = { version = "1.4.4", features = ["postgres", "r2d2", "chrono", "uuid", "numeric","serde_json"] }
uuid = { version = "^0.6", features = ["serde", "v4"] }
dotenv = "0.15.0"
r2d2 = "0.8.9"
chrono = "0.4.0"
regex = "^1"