[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web= "^4"
serde = { version = "^1", features = ["derive"]}
serde_json = "^1"
env_logger = "0.9.0"
log = "^0.4"
strum_macros = "^0.24"
strum = { version = "^0.24.1", features = ["derive"]}
derive_more = "^0.99"
diesel = { version = "1.4.4", features = ["postgres", "r2d2", "chrono", "uuid"] }
uuid = { version = "^0.6", features = ["serde", "v4"] }
dotenv = "0.15.0"
r2d2 = "0.8.9"
deadpool-postgres = { version = "0.10.2", features = ["serde"] }
config = "0.13.1"
chrono = "0.4.0"