[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web= "^4"
uuid = { version = "1.1.2", features = ["v4"]}
serde = { version = "^1", features = ["derive"]}
env_logger = "0.9.0"
log = "^0.4"
strum_macros = "^0.24"
strum = { version = "^0.24.1", features = ["derive"]}
derive_more = "^0.99"
diesel = { version = "1.4.8", features = ["postgres", "r2d2",] }
dotenv = "0.15.0"
r2d2 = "0.8.9"
deadpool-postgres = { version = "0.10.2", features = ["serde"] }
tokio-pg-mapper = "0.2.0"
tokio-pg-mapper-derive = "0.2.0"
tokio-postgres = "0.7.6"
config = "0.13.1"